### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by adamlawson50** [andreapizzato/tez-recovery#5]
![ScreeenShotError](https://user-images.githubusercontent.com/50337259/60547584-f8790480-9d17-11e9-86ca-0e8615cf2b32.JPG)
When running the process, I get "[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues." as line 1 (matrix brut force)  but then a second line appears with a progress bar which I assume is the non-matrix password brut force. 

When I created the password matrix, I listed all the parts of passwords I could think of but then when I click enter it just takes me to a command line, no further options. So I entered the command npm start recovery and the above action started. 

Second question - is there a way to speed it up ? GPU process only at 1%, CPU at 10%, Memory at 50% when in progress - can I allocate more power to this process ?

**Comment by cedricwinterwolf** [comment]
Same question. And at some point it stopped processing and I got a new error:

 throw err;
  ^

Error: Cannot find module 'C:\Users\Kedrik\...'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1065:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:911:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
